server:
  port: 8090

spring:
  #图片上传
  servlet:
    multipart:
      max-request-size: 10MB
      file-size-threshold: 10MB
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #缓存模式为redis
  cache:
    type: redis
  #redis
  redis:
    host: XX.XX.XXX.XXx
    port: 6379
    database: 0
    password: xxxxx
    timeout: 100s
    #连接池配置
    jedis:
      pool:
        #最大空闲连接数
        max-idle: 500
        #最小空闲连接数
        min-idle: 50
        #等待可用连接最大时间，负数为无限制
        max-wait: -1s
        #最大活跃连接时间
        max-active: -1




  #thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html

  #json返回时间格式设置
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  #关闭title的小图标，使用自己的图标，需要在resources导入自己的图标--logo.ico
  mvc:
    favicon:
      enabled: false

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.parking.entity
  configuration:
    map-underscore-to-camel-case: true  #使用驼峰法映射属性
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1

#分页插件
pagehelper:
  helper-dialect: mysql
  params: count= countSql
  reasonable: true
  support-methods-arguments: true




  #显示SQL语句日志，扫描项目mapper包下的所有类，对SQL语句进行控制台打印
  logging:
    level:
  com.cmh.mapper: debug


